//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppFiplasto.Droid.WebServiceSpif {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://www.sistemasfiplasto.com.ar/wsspif")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RemPendEnPieyProveedoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback HacherosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RajadoraOperationCompleted;
        
        private System.Threading.SendOrPostCallback EntrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsAuthenticatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback EntrarTelefonoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://www.sistemasfiplasto.com.ar/wsspif/service1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RemPendEnPieyProveedoresCompletedEventHandler RemPendEnPieyProveedoresCompleted;
        
        /// <remarks/>
        public event HacherosCompletedEventHandler HacherosCompleted;
        
        /// <remarks/>
        public event RajadoraCompletedEventHandler RajadoraCompleted;
        
        /// <remarks/>
        public event EntrarCompletedEventHandler EntrarCompleted;
        
        /// <remarks/>
        public event IsAuthenticatedCompletedEventHandler IsAuthenticatedCompleted;
        
        /// <remarks/>
        public event EntrarTelefonoCompletedEventHandler EntrarTelefonoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/RemPendEnPieyProveedores", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RemPendEnPieyProveedores(string opcion, string fecha) {
            object[] results = this.Invoke("RemPendEnPieyProveedores", new object[] {
                        opcion,
                        fecha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RemPendEnPieyProveedoresAsync(string opcion, string fecha) {
            this.RemPendEnPieyProveedoresAsync(opcion, fecha, null);
        }
        
        /// <remarks/>
        public void RemPendEnPieyProveedoresAsync(string opcion, string fecha, object userState) {
            if ((this.RemPendEnPieyProveedoresOperationCompleted == null)) {
                this.RemPendEnPieyProveedoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemPendEnPieyProveedoresOperationCompleted);
            }
            this.InvokeAsync("RemPendEnPieyProveedores", new object[] {
                        opcion,
                        fecha}, this.RemPendEnPieyProveedoresOperationCompleted, userState);
        }
        
        private void OnRemPendEnPieyProveedoresOperationCompleted(object arg) {
            if ((this.RemPendEnPieyProveedoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemPendEnPieyProveedoresCompleted(this, new RemPendEnPieyProveedoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/Hacheros", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Hacheros(string Estructura) {
            object[] results = this.Invoke("Hacheros", new object[] {
                        Estructura});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void HacherosAsync(string Estructura) {
            this.HacherosAsync(Estructura, null);
        }
        
        /// <remarks/>
        public void HacherosAsync(string Estructura, object userState) {
            if ((this.HacherosOperationCompleted == null)) {
                this.HacherosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHacherosOperationCompleted);
            }
            this.InvokeAsync("Hacheros", new object[] {
                        Estructura}, this.HacherosOperationCompleted, userState);
        }
        
        private void OnHacherosOperationCompleted(object arg) {
            if ((this.HacherosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HacherosCompleted(this, new HacherosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/Rajadora", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Rajadora(string fecha) {
            object[] results = this.Invoke("Rajadora", new object[] {
                        fecha});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RajadoraAsync(string fecha) {
            this.RajadoraAsync(fecha, null);
        }
        
        /// <remarks/>
        public void RajadoraAsync(string fecha, object userState) {
            if ((this.RajadoraOperationCompleted == null)) {
                this.RajadoraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRajadoraOperationCompleted);
            }
            this.InvokeAsync("Rajadora", new object[] {
                        fecha}, this.RajadoraOperationCompleted, userState);
        }
        
        private void OnRajadoraOperationCompleted(object arg) {
            if ((this.RajadoraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RajadoraCompleted(this, new RajadoraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/Entrar", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Entrar(string usuario, string clave) {
            object[] results = this.Invoke("Entrar", new object[] {
                        usuario,
                        clave});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EntrarAsync(string usuario, string clave) {
            this.EntrarAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void EntrarAsync(string usuario, string clave, object userState) {
            if ((this.EntrarOperationCompleted == null)) {
                this.EntrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntrarOperationCompleted);
            }
            this.InvokeAsync("Entrar", new object[] {
                        usuario,
                        clave}, this.EntrarOperationCompleted, userState);
        }
        
        private void OnEntrarOperationCompleted(object arg) {
            if ((this.EntrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntrarCompleted(this, new EntrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/IsAuthenticated", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsAuthenticated(string Domain, string username, string pwd) {
            object[] results = this.Invoke("IsAuthenticated", new object[] {
                        Domain,
                        username,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsAuthenticatedAsync(string Domain, string username, string pwd) {
            this.IsAuthenticatedAsync(Domain, username, pwd, null);
        }
        
        /// <remarks/>
        public void IsAuthenticatedAsync(string Domain, string username, string pwd, object userState) {
            if ((this.IsAuthenticatedOperationCompleted == null)) {
                this.IsAuthenticatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAuthenticatedOperationCompleted);
            }
            this.InvokeAsync("IsAuthenticated", new object[] {
                        Domain,
                        username,
                        pwd}, this.IsAuthenticatedOperationCompleted, userState);
        }
        
        private void OnIsAuthenticatedOperationCompleted(object arg) {
            if ((this.IsAuthenticatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAuthenticatedCompleted(this, new IsAuthenticatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sistemasfiplasto.com.ar/wsspif/EntrarTelefono", RequestNamespace="http://www.sistemasfiplasto.com.ar/wsspif", ResponseNamespace="http://www.sistemasfiplasto.com.ar/wsspif", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EntrarTelefono(string usuario, string clave) {
            object[] results = this.Invoke("EntrarTelefono", new object[] {
                        usuario,
                        clave});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EntrarTelefonoAsync(string usuario, string clave) {
            this.EntrarTelefonoAsync(usuario, clave, null);
        }
        
        /// <remarks/>
        public void EntrarTelefonoAsync(string usuario, string clave, object userState) {
            if ((this.EntrarTelefonoOperationCompleted == null)) {
                this.EntrarTelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntrarTelefonoOperationCompleted);
            }
            this.InvokeAsync("EntrarTelefono", new object[] {
                        usuario,
                        clave}, this.EntrarTelefonoOperationCompleted, userState);
        }
        
        private void OnEntrarTelefonoOperationCompleted(object arg) {
            if ((this.EntrarTelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EntrarTelefonoCompleted(this, new EntrarTelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RemPendEnPieyProveedoresCompletedEventHandler(object sender, RemPendEnPieyProveedoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemPendEnPieyProveedoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemPendEnPieyProveedoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void HacherosCompletedEventHandler(object sender, HacherosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HacherosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HacherosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RajadoraCompletedEventHandler(object sender, RajadoraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RajadoraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RajadoraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EntrarCompletedEventHandler(object sender, EntrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void IsAuthenticatedCompletedEventHandler(object sender, IsAuthenticatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAuthenticatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAuthenticatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EntrarTelefonoCompletedEventHandler(object sender, EntrarTelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EntrarTelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EntrarTelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591