//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppFiplasto.Droid.WebServiceXamarin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListaStockMaderaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemitosBiomasaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabarTicketBioOperationCompleted;
        
        private System.Threading.SendOrPostCallback PermisosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RQPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutorizaRQOperationCompleted;
        
        private System.Threading.SendOrPostCallback InformeProduccionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = "http://www.sistemasfiplasto.com.ar/xamarin/WebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListaStockMaderaCompletedEventHandler ListaStockMaderaCompleted;
        
        /// <remarks/>
        public event RemitosBiomasaCompletedEventHandler RemitosBiomasaCompleted;
        
        /// <remarks/>
        public event GrabarTicketBioCompletedEventHandler GrabarTicketBioCompleted;
        
        /// <remarks/>
        public event PermisosCompletedEventHandler PermisosCompleted;
        
        /// <remarks/>
        public event RQPendientesCompletedEventHandler RQPendientesCompleted;
        
        /// <remarks/>
        public event AutorizaRQCompletedEventHandler AutorizaRQCompleted;
        
        /// <remarks/>
        public event InformeProduccionCompletedEventHandler InformeProduccionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaStockMadera", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ListaStockMadera() {
            object[] results = this.Invoke("ListaStockMadera", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ListaStockMaderaAsync() {
            this.ListaStockMaderaAsync(null);
        }
        
        /// <remarks/>
        public void ListaStockMaderaAsync(object userState) {
            if ((this.ListaStockMaderaOperationCompleted == null)) {
                this.ListaStockMaderaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaStockMaderaOperationCompleted);
            }
            this.InvokeAsync("ListaStockMadera", new object[0], this.ListaStockMaderaOperationCompleted, userState);
        }
        
        private void OnListaStockMaderaOperationCompleted(object arg) {
            if ((this.ListaStockMaderaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaStockMaderaCompleted(this, new ListaStockMaderaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemitosBiomasa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RemitosBiomasa() {
            object[] results = this.Invoke("RemitosBiomasa", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RemitosBiomasaAsync() {
            this.RemitosBiomasaAsync(null);
        }
        
        /// <remarks/>
        public void RemitosBiomasaAsync(object userState) {
            if ((this.RemitosBiomasaOperationCompleted == null)) {
                this.RemitosBiomasaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemitosBiomasaOperationCompleted);
            }
            this.InvokeAsync("RemitosBiomasa", new object[0], this.RemitosBiomasaOperationCompleted, userState);
        }
        
        private void OnRemitosBiomasaOperationCompleted(object arg) {
            if ((this.RemitosBiomasaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemitosBiomasaCompleted(this, new RemitosBiomasaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GrabarTicketBio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GrabarTicketBio(string ticket, string turno, string grupo, string fechapicado) {
            object[] results = this.Invoke("GrabarTicketBio", new object[] {
                        ticket,
                        turno,
                        grupo,
                        fechapicado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GrabarTicketBioAsync(string ticket, string turno, string grupo, string fechapicado) {
            this.GrabarTicketBioAsync(ticket, turno, grupo, fechapicado, null);
        }
        
        /// <remarks/>
        public void GrabarTicketBioAsync(string ticket, string turno, string grupo, string fechapicado, object userState) {
            if ((this.GrabarTicketBioOperationCompleted == null)) {
                this.GrabarTicketBioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabarTicketBioOperationCompleted);
            }
            this.InvokeAsync("GrabarTicketBio", new object[] {
                        ticket,
                        turno,
                        grupo,
                        fechapicado}, this.GrabarTicketBioOperationCompleted, userState);
        }
        
        private void OnGrabarTicketBioOperationCompleted(object arg) {
            if ((this.GrabarTicketBioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabarTicketBioCompleted(this, new GrabarTicketBioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Permisos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Permisos(string usuario) {
            object[] results = this.Invoke("Permisos", new object[] {
                        usuario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PermisosAsync(string usuario) {
            this.PermisosAsync(usuario, null);
        }
        
        /// <remarks/>
        public void PermisosAsync(string usuario, object userState) {
            if ((this.PermisosOperationCompleted == null)) {
                this.PermisosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPermisosOperationCompleted);
            }
            this.InvokeAsync("Permisos", new object[] {
                        usuario}, this.PermisosOperationCompleted, userState);
        }
        
        private void OnPermisosOperationCompleted(object arg) {
            if ((this.PermisosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PermisosCompleted(this, new PermisosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RQPendientes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RQPendientes(string esquemaAutorizacion) {
            object[] results = this.Invoke("RQPendientes", new object[] {
                        esquemaAutorizacion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RQPendientesAsync(string esquemaAutorizacion) {
            this.RQPendientesAsync(esquemaAutorizacion, null);
        }
        
        /// <remarks/>
        public void RQPendientesAsync(string esquemaAutorizacion, object userState) {
            if ((this.RQPendientesOperationCompleted == null)) {
                this.RQPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRQPendientesOperationCompleted);
            }
            this.InvokeAsync("RQPendientes", new object[] {
                        esquemaAutorizacion}, this.RQPendientesOperationCompleted, userState);
        }
        
        private void OnRQPendientesOperationCompleted(object arg) {
            if ((this.RQPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RQPendientesCompleted(this, new RQPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizaRQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AutorizaRQ(string esquemaAutorizacion, string modfor, string codfor, string nrofor, string user) {
            object[] results = this.Invoke("AutorizaRQ", new object[] {
                        esquemaAutorizacion,
                        modfor,
                        codfor,
                        nrofor,
                        user});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AutorizaRQAsync(string esquemaAutorizacion, string modfor, string codfor, string nrofor, string user) {
            this.AutorizaRQAsync(esquemaAutorizacion, modfor, codfor, nrofor, user, null);
        }
        
        /// <remarks/>
        public void AutorizaRQAsync(string esquemaAutorizacion, string modfor, string codfor, string nrofor, string user, object userState) {
            if ((this.AutorizaRQOperationCompleted == null)) {
                this.AutorizaRQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizaRQOperationCompleted);
            }
            this.InvokeAsync("AutorizaRQ", new object[] {
                        esquemaAutorizacion,
                        modfor,
                        codfor,
                        nrofor,
                        user}, this.AutorizaRQOperationCompleted, userState);
        }
        
        private void OnAutorizaRQOperationCompleted(object arg) {
            if ((this.AutorizaRQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizaRQCompleted(this, new AutorizaRQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InformeProduccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet InformeProduccion(string UltimoDiaMesAnterior, string FechaHasta) {
            object[] results = this.Invoke("InformeProduccion", new object[] {
                        UltimoDiaMesAnterior,
                        FechaHasta});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void InformeProduccionAsync(string UltimoDiaMesAnterior, string FechaHasta) {
            this.InformeProduccionAsync(UltimoDiaMesAnterior, FechaHasta, null);
        }
        
        /// <remarks/>
        public void InformeProduccionAsync(string UltimoDiaMesAnterior, string FechaHasta, object userState) {
            if ((this.InformeProduccionOperationCompleted == null)) {
                this.InformeProduccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInformeProduccionOperationCompleted);
            }
            this.InvokeAsync("InformeProduccion", new object[] {
                        UltimoDiaMesAnterior,
                        FechaHasta}, this.InformeProduccionOperationCompleted, userState);
        }
        
        private void OnInformeProduccionOperationCompleted(object arg) {
            if ((this.InformeProduccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InformeProduccionCompleted(this, new InformeProduccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ListaStockMaderaCompletedEventHandler(object sender, ListaStockMaderaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaStockMaderaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaStockMaderaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RemitosBiomasaCompletedEventHandler(object sender, RemitosBiomasaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemitosBiomasaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemitosBiomasaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GrabarTicketBioCompletedEventHandler(object sender, GrabarTicketBioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrabarTicketBioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrabarTicketBioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PermisosCompletedEventHandler(object sender, PermisosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PermisosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PermisosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RQPendientesCompletedEventHandler(object sender, RQPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RQPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RQPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AutorizaRQCompletedEventHandler(object sender, AutorizaRQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizaRQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutorizaRQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void InformeProduccionCompletedEventHandler(object sender, InformeProduccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InformeProduccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InformeProduccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591